### ISSUE TITLE
question regarding your code

### ISSUE THREAD

**Issue by bruno-31** [thstkdgus35/bicubic_pytorch#1]
Thank you for the great work !

I have noticed that your implementation is significantly slower than pytorch on large images. Would you have any ideas for accelerating your implementation ?

I'm also curious about the antialiasing : how is it implemented in your code, i mean what is the general method that you use ? (I don't have acess to the matlab source code).

Thanks 

Bruno

**Comment by sanghyun-son** [comment]
Thank you for your interest in my code!

Simply speaking, the antialiasing option expands the receptive field s times larger, where s is a downsampling factor (It is ignored when you upscale the image).

For example, the default bicubic kernel is 4 x 4, but it will become 8 x 8 when you enable the antialiasing during the x2 downsampling.

In detail, the antialiasing is more closely related to the coordinate system (which allows fractional downsampling factors).

I think [these](https://github.com/thstkdgus35/bicubic_pytorch/blob/54980abda75a1a86f4b6d9f510ac1a39c819abf1/core.py#L230-L232) and[ these](https://github.com/thstkdgus35/bicubic_pytorch/blob/54980abda75a1a86f4b6d9f510ac1a39c819abf1/core.py#L169-L174) lines can provide you more intuition.

Please feel free to ask any details if you want further clarification.

Thank you!

Sanghyun
