### ISSUE TITLE
About torch.logical_and function in Pytorch 0.4.1

### ISSUE THREAD

**Issue by JerkBang** [thstkdgus35/bicubic_pytorch#2]
Hello, really appreciate sharing your code of bicubic_pytorch and found a problem about it. I copied the core.py to my project and run it but occured error that there is not logical_and in Pytorch 0.4.1.
   I solved it from https://stackoverflow.com/questions/54590661/pytorch-equivalent-of-numpys-logical-and-and-kin. The approach is replace "torch.logical_and(a, b)" with "a & b".
   hope it helps for all.

**Comment by JerkBang** [comment]
> ```
> Hello, really appreciate sharing your code of bicubic_pytorch and found a problem about it. I copied the core.py to my project and run it but occured error that there is not logical_and in Pytorch 0.4.1.
> ```
> 
> I solved it from https://stackoverflow.com/questions/54590661/pytorch-equivalent-of-numpys-logical-and-and-kin. The approach is replace "torch.logical_and(a, b)" with "a & b".
> hope it helps for all.

Sorry, first time to commit issue, didn't know the fisrt row of text would be the code present. That's a prologue : )

**Comment by sanghyun-son** [comment]
Hi @JerkBang,

I really appreciate that you have found my code useful.

Please feel free to ask about any issues with legacy PyTorch versions!

Thank you.
